version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: todoBasicsBackend
    restart: always
    environment:
      POSTGRES_DB: todoBasicsBackend
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local