spring:
  application:
    name: todoBasicsBackend

  datasource:
    url: jdbc:postgresql://localhost:5432/todoBasicsBackend
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Optional: Enable detailed logs for debugging
  sql:
    init:
      mode: always

# Optional: Enable H2 Console if using H2 for testing
# spring:
#   h2:
#     console:
#       enabled: true